"""Add dictionary models

Revision ID: 32361ce36344
Revises: 0de9a6a4199c
Create Date: 2025-10-28 18:25:00.216124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32361ce36344'
down_revision = '0de9a6a4199c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('SAUSAGE', 'DRINKS', 'CHEESE', 'SEAFOOD', 'CONFECTIONERY', 'RESTAURANT', 'GROCERY', 'SERVICES', 'OTHER', name='businesscategoryenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('counterparty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LLC', 'IP', name='counterpartytype'), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('contacts', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn')
    )
    op.create_table('property_object_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('LED_SCREEN', 'PAVILION', 'SHIELD', 'BOX', 'BANNER', 'SIGNBOARD', 'INTERIOR', 'OTHER', name='propertyobjecttypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('PLACEMENT', 'DESIGN', 'INSTALLATION', 'DISMANTLING', 'MANUFACTURING', 'PRODUCTION', 'CONSULTATION', 'OTHER', name='servicetypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('property_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('characteristics', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['property_object_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_object')
    op.drop_table('service_type')
    op.drop_table('property_object_type')
    op.drop_table('counterparty')
    op.drop_table('business_category')
    # ### end Alembic commands ###
