"""add payment model and paid_amount to realization

Revision ID: 5eac254326c8
Revises: e74b5588a901
Create Date: 2025-10-30 15:05:11.236074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eac254326c8'
down_revision = 'e74b5588a901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем существование таблиц (на случай частично выполненной миграции)
    from sqlalchemy import inspect
    inspector = inspect(op.get_bind())
    existing_tables = inspector.get_table_names()
    
    if 'payment' not in existing_tables:
        op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('initial_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unallocated_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('CASH', 'NON_CASH', name='paymenttype'), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'payment_realization_association' not in existing_tables:
        op.create_table('payment_realization_association',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('realization_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['realization_id'], ['realization.id'], ),
        sa.PrimaryKeyConstraint('payment_id', 'realization_id')
        )
    
    # Проверяем существование колонки paid_amount
    realization_columns = [col['name'] for col in inspector.get_columns('realization')]
    if 'paid_amount' not in realization_columns:
        # SQLite не поддерживает добавление NOT NULL колонки напрямую
        # Сначала добавляем nullable, обновляем значения, затем делаем NOT NULL
        with op.batch_alter_table('realization', schema=None) as batch_op:
            batch_op.add_column(sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0'))
    
        # Обновляем все существующие записи
        op.execute("UPDATE realization SET paid_amount = 0 WHERE paid_amount IS NULL")
        
        # Теперь делаем NOT NULL
        with op.batch_alter_table('realization', schema=None) as batch_op:
            batch_op.alter_column('paid_amount', nullable=False, server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realization', schema=None) as batch_op:
        batch_op.drop_column('paid_amount')

    op.drop_table('payment_realization_association')
    op.drop_table('payment')
    # ### end Alembic commands ###
