"""remove payment_type from realization

Revision ID: 87637e09c7ec
Revises: bd6adf8ba9f2
Create Date: 2025-10-30 14:04:40.056237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87637e09c7ec'
down_revision = 'bd6adf8ba9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realization', schema=None) as batch_op:
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.VARCHAR(length=8), nullable=False))

    # ### end Alembic commands ###
