"""Add realization models

Revision ID: bd6adf8ba9f2
Revises: fd559c020ce4
Create Date: 2025-10-29 12:16:53.364847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6adf8ba9f2'
down_revision = 'fd559c020ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('AUTO', 'MANUAL', 'ONCE', name='realizationsource'), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.Enum('CASH', 'NON_CASH', name='paymenttype'), nullable=False),
    sa.Column('payment_status', sa.Enum('NOT_PAID', 'PARTIALLY_PAID', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('specification_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['specification.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('realization_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sale_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expense_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('realization_id', sa.Integer(), nullable=False),
    sa.Column('property_object_id', sa.Integer(), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_object_id'], ['property_object.id'], ),
    sa.ForeignKeyConstraint(['realization_id'], ['realization.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('realization_service')
    op.drop_table('realization')
    # ### end Alembic commands ###
